name: Run Koyeb Script

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # 每周一运行一次
  push:
    branches:
      - main

jobs:
  login:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'  # 建议使用具体的 Python 版本

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: 运行 Koyeb 脚本
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          KOYEB_API_TOKEN: ${{ secrets.KOYEB_API_TOKEN }}  # 从GitHub Secrets中获取API Token
        run: |
          python api.py  # 替换为实际脚本名称
